AWS_ACCESS_KEY_ID: "your_aws_access_key_id"
AWS_SECRET_ACCESS_KEY: "your_aws_secret_access_key"
S3_BUCKET_NAME: "your_s3_bucket_name"
FACEBOOK_CLIENT_ID: "your_facebook_client_id"
FACEBOOK_CLIENT_SECRET: "your_facebook_client_secret"
GOOGLE_CLIENT_ID: "your_google_client_id"
GOOGLE_CLIENT_SECRET: "your_google_client_id""
